# set up the default terminal
ENV["TERM"]="linux"

Vagrant.configure("2") do |config|

  # set the image for the vagrant box
  config.vm.box = "opensuse/Leap-15.2.x86_64"
  config.vm.hostname = "Opensuse-Leap-15.2-x86-64"

  ## Set the image version
  # config.vm.box_version = "15.2.31.212"

  # st the static IP for the vagrant box
  config.vm.network "private_network", ip: "192.168.50.4"

  # consifure the parameters for VirtualBox provider
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Opensuse-Leap-15.2"
    vb.memory = "2096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
  end
end
