apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{ .Values.image.repository }}"
    tag: "{{ .Values.image.tag }}"
  name: "{{ .Values.image.repository }}-{{ .Values.image.tag }}"
  namespace: "{{ .Values.namespace.name }}"
spec:
  ports:
    - port: { { .Values.service.port } }
      protocol: TCP
      targetPort: 8111
  selector:
    app: "{{ .Values.image.repository }}"
    tag: "{{ .Values.image.tag }}"
  type: { { .Values.service.type } }
