namespace:
  name: demo

image:
  repository: nginx
  tag: alpine

replicaCount: 3
imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 256Mi

service:
  type: ClusterIP
  port: 8111
